"""Ensure SenderID is Integer

Revision ID: 8251f160f0a1
Revises: d3deda7a8c17
Create Date: 2024-08-22 11:58:31.780540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8251f160f0a1'
down_revision = 'd3deda7a8c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_msg', schema=None) as batch_op:
        batch_op.alter_column('GroupID',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('MessageID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('ChatContentID',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_msg', schema=None) as batch_op:
        batch_op.alter_column('ChatContentID',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('MessageID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('GroupID',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
