"""改正 user_msg 表的主鍵設置

Revision ID: 9fa8d42b1c54
Revises: 877be2afe93b
Create Date: 2024-08-23 15:18:43.081976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fa8d42b1c54'
down_revision = '877be2afe93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_msg', schema=None) as batch_op:
        
        batch_op.create_primary_key('pk_user_msg', ['MessageID'])
        # 設置 MessageID 為主鍵
        batch_op.alter_column('MessageID',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        

        # 修改 GroupID 的長度
        batch_op.alter_column('GroupID',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

        # 修改 ChatContentID 的長度
        batch_op.alter_column('ChatContentID',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=False)

        # 修改 Emotion 的長度
        batch_op.alter_column('Emotion',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

        # 創建 GroupID 的索引
        batch_op.create_index(batch_op.f('ix_user_msg_GroupID'), ['GroupID'], unique=False)

    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_msg', schema=None) as batch_op:
        # 刪除 GroupID 的索引
        batch_op.drop_index(batch_op.f('ix_user_msg_GroupID'))

        # 刪除 MessageID 主鍵
        batch_op.drop_constraint('pk_user_msg', type_='primary')

        # 將 Emotion 長度恢復為 10
        batch_op.alter_column('Emotion',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

        # 將 ChatContentID 長度恢復為 250
        batch_op.alter_column('ChatContentID',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)

        # 將 GroupID 長度恢復為 20
        batch_op.alter_column('GroupID',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

        # 恢復 MessageID 設置
        batch_op.alter_column('MessageID',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


    # ### end Alembic commands ###
