"""Change SenderID to varchar(50)

Revision ID: d3deda7a8c17
Revises: 9b50692e1aef
Create Date: 2024-08-22 11:48:18.022783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3deda7a8c17'
down_revision = '9b50692e1aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_msg', schema=None) as batch_op:
        batch_op.alter_column('SenderID',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('ChatContentID',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_msg', schema=None) as batch_op:
        batch_op.alter_column('ChatContentID',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('SenderID',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
